phpseclib/phpseclib

- phpseclib/Crypt/Base.php
- phpseclib/Crypt/RSA.php
- phpseclib/File/ASN1.php
- phpseclib/File/X509.php
- phpseclib/Math/BigInteger.php
- phpseclib/Net/SCP.php
- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH2.php
This PR replaces get_class() calls with instanceof operators.
Fixes #570.
> Replaced get_class() calls with instanceof operators

- phpseclib/Net/SSH2.php
> SSH2: update conditions under which _disconnect's code is executed

- phpseclib/Crypt/RSA.php
- phpseclib/Math/BigInteger.php
See issue [#597](https://github.com/phpseclib/phpseclib/issues/597)
> (OpenSSL Big integer) Only require major version to match

- .scrutinizer.yml
- .travis.yml
- composer.json
- composer.lock
> Remove old branch alias from 1.0 branch

- CHANGELOG.md
> CHANGELOG: add 0.3.10 release

- phpseclib/Crypt/DES.php
Fixes #632. No unit test is currently included. I'll add this to the openssl-support and setengine PR's however.
> DES: fix fatal error that could occur under special circumstances

- phpseclib/Net/SSH2.php
- phpseclib/System/SSH/Agent.php
- tests/Functional/Net/SSH2AgentTest.php
A clean single commit version of SSH agent forwarding implementation work.
> SSH agent forwarding implementation

- phpseclib/Net/SSH2.php
See #634 and https://tools.ietf.org/html/rfc4253#section-4.2
> improve error handling with protocol version exchange

- phpseclib/Net/SSH2.php
> SSH2: NET_SSH2_MASK_* -> self::MASK_*

- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/DES.php
Replaces #507 . Hopefully using phpseclib:1.0 as the target will re-enable unit tests, among other things..
> add OpenSSL support for symmetric key encryption

- phpseclib/Net/SFTP.php
> Add callback to SFTP.php for 1.0 branch

- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/Rijndael.php
- phpseclib/Net/SCP.php
- tests/Functional/Net/SFTPLargeFileTest.php
- tests/Functional/Net/SFTPUserStoryTest.php
- tests/Functional/Net/SSH2Test.php
- tests/PhpseclibFunctionalTestCase.php
- tests/PhpseclibTestCase.php
- tests/Unit/Crypt/AES/TestCase.php
- tests/Unit/Crypt/Hash/MD5Test.php
- tests/Unit/Crypt/Hash/SHA256Test.php
- tests/Unit/Crypt/Hash/SHA256_96Test.php
- tests/Unit/Crypt/Hash/SHA512Test.php
- tests/Unit/Crypt/Hash/SHA512_96Test.php
- tests/Unit/Crypt/RSA/LoadKeyTest.php
- tests/Unit/Crypt/RandomTest.php
- tests/Unit/File/ASN1Test.php
- tests/Unit/Math/BigInteger/TestCase.php
> Fixed some phpdocs for 2.0

- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/Rijndael.php
- phpseclib/Net/SCP.php
- tests/Functional/Net/SFTPLargeFileTest.php
- tests/Functional/Net/SFTPUserStoryTest.php
- tests/Functional/Net/SSH2Test.php
- tests/PhpseclibFunctionalTestCase.php
- tests/PhpseclibTestCase.php
- tests/Unit/Crypt/AES/TestCase.php
- tests/Unit/Crypt/Hash/MD5Test.php
- tests/Unit/Crypt/Hash/SHA256Test.php
- tests/Unit/Crypt/Hash/SHA256_96Test.php
- tests/Unit/Crypt/Hash/SHA512Test.php
- tests/Unit/Crypt/Hash/SHA512_96Test.php
- tests/Unit/Crypt/RSA/LoadKeyTest.php
- tests/Unit/Crypt/RandomTest.php
- tests/Unit/File/ASN1Test.php
- tests/Unit/Math/BigInteger/TestCase.php
Once this is merged, I can deal with the dodgie scalar types in the docblocks. :)
> Fixed some phpdocs

- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/Rijndael.php
- phpseclib/Net/SCP.php
- tests/Functional/Net/SFTPLargeFileTest.php
- tests/Functional/Net/SFTPUserStoryTest.php
- tests/Functional/Net/SSH2Test.php
- tests/PhpseclibFunctionalTestCase.php
- tests/PhpseclibTestCase.php
- tests/Unit/Crypt/AES/TestCase.php
- tests/Unit/Crypt/Hash/MD5Test.php
- tests/Unit/Crypt/Hash/SHA256Test.php
- tests/Unit/Crypt/Hash/SHA256_96Test.php
- tests/Unit/Crypt/Hash/SHA512Test.php
- tests/Unit/Crypt/Hash/SHA512_96Test.php
- tests/Unit/Crypt/RSA/LoadKeyTest.php
- tests/Unit/Crypt/RandomTest.php
- tests/Unit/File/ASN1Test.php
- tests/Unit/Math/BigInteger/TestCase.php
> Fixed some phpdocs for 1.0

- phpseclib/Net/SSH2.php
> fix E_NOTICE with SSH2 global requests

- phpseclib/Crypt/RSA.php
- tests/Unit/Crypt/RSA/ModeTest.php
> add "none" encryption mode for 1.0 branch

- phpseclib/Crypt/RC4.php
Looks like they got skipped over when the merge conflict was resolved
> RC4: re-add the OpenSSL changes for RC4

- phpseclib/Net/SSH2.php
> SSH2: fix for window sizes > 2,147,483,648 for 1.0 branch

- phpseclib/File/X509.php
- tests/Unit/File/X509/X509Test.php
> set signaturealgorithm parameters field to null / 1.0 branch

- phpseclib/Net/SFTP/Stream.php
- tests/Functional/Net/SFTPLargeFileTest.php
- tests/Functional/Net/SFTPStreamTest.php
- tests/Functional/Net/SFTPTestCase.php
> [2.0] Various fixes to fopen mode handling in SFTP Stream

- phpseclib/Net/SFTP.php
> SFTP: don't update stat cache when it's been disabled

- phpseclib/Net/SSH2.php
> Add support for RFC 4419: diffie-hellman-group-exchange-sha{1,256}

- phpseclib/Net/SFTP.php
- tests/Functional/Net/SFTPUserStoryTest.php
Replaces #738 which had duplicated some existing commits using interactive rebase.
> SFTP: stat cache updates

- phpseclib/Net/SSH2.php
- tests/Functional/Net/SSH2Test.php
> SSH2: make it so you can connect using open sockets / 1.0 branch

- composer.json
- composer.lock
- phpseclib/Net/SSH2.php
- tests/Unit/Net/SSH2Test.php
Fix #610
See https://github.com/jedisct1/libsodium-php
> [2.0] SSH2: Add support for curve25519-sha256@libssh.org.txt via libsodium-php.

- phpseclib/Crypt/RSA.php
- tests/Unit/Crypt/RSA/ModeTest.php
Fix #768 
A unit test would be nice. Maybe I can do one today but maybe not.
> RSA: fix regression for PSS signatures

- phpseclib/File/X509.php
- tests/Unit/File/X509/X509Test.php
> X509: add getOID() method

- .travis.yml
- travis/run-phpunit.sh
Cherry pick of 2813e2cd3b829b3fd3e89bb66762f7b38e234ce6.
> Backport to 2.0: Add PHP7 to Travis CI.

- phpseclib/Crypt/AES.php
- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/DES.php
- phpseclib/Crypt/Hash.php
- phpseclib/Crypt/RC2.php
- phpseclib/Crypt/RC4.php
- phpseclib/Crypt/RSA.php
- phpseclib/Crypt/Random.php
- phpseclib/Crypt/Rijndael.php
- phpseclib/Crypt/TripleDES.php
- phpseclib/Crypt/Twofish.php
- phpseclib/File/ANSI.php
- phpseclib/File/ASN1.php
- phpseclib/File/X509.php
- phpseclib/Math/BigInteger.php
- phpseclib/Net/SCP.php
- phpseclib/Net/SFTP.php
- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH1.php
- phpseclib/Net/SSH2.php
- phpseclib/System/SSH/Agent.php
Made possible by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1373, where case sensitive is set to false.
> [1.0] PHPDoc Fixes

- phpseclib/Crypt/AES.php
- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/DES.php
- phpseclib/Crypt/Hash.php
- phpseclib/Crypt/RC2.php
- phpseclib/Crypt/RC4.php
- phpseclib/Crypt/RSA.php
- phpseclib/Crypt/Random.php
- phpseclib/Crypt/Rijndael.php
- phpseclib/Crypt/TripleDES.php
- phpseclib/Crypt/Twofish.php
- phpseclib/File/ANSI.php
- phpseclib/File/ASN1.php
- phpseclib/File/ASN1/Element.php
- phpseclib/File/X509.php
- phpseclib/Math/BigInteger.php
- phpseclib/Net/SCP.php
- phpseclib/Net/SFTP.php
- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH1.php
- phpseclib/Net/SSH2.php
- phpseclib/System/SSH/Agent.php
- phpseclib/System/SSH/Agent/Identity.php
Made possible by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1373, where case sensitive is set to false.
> [3.0] PHPDoc Fixes

- phpseclib/Crypt/AES.php
- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/DES.php
- phpseclib/Crypt/Hash.php
- phpseclib/Crypt/RC2.php
- phpseclib/Crypt/RC4.php
- phpseclib/Crypt/RSA.php
- phpseclib/Crypt/Random.php
- phpseclib/Crypt/Rijndael.php
- phpseclib/Crypt/TripleDES.php
- phpseclib/Crypt/Twofish.php
- phpseclib/File/ANSI.php
- phpseclib/File/ASN1.php
- phpseclib/File/ASN1/Element.php
- phpseclib/File/X509.php
- phpseclib/Math/BigInteger.php
- phpseclib/Net/SCP.php
- phpseclib/Net/SFTP.php
- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH1.php
- phpseclib/Net/SSH2.php
- phpseclib/System/SSH/Agent.php
- phpseclib/System/SSH/Agent/Identity.php
Made possible by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/1373, where case sensitive is set to false.
> [2.0] PHPDoc Fixes

- phpseclib/Crypt/RSA.php
- phpseclib/Crypt/Random.php
- phpseclib/Math/BigInteger.php
- tests/PhpseclibTestCase.php
- tests/Unit/Math/BigInteger/InternalOpenSSLTest.php
Exactly the same as https://github.com/phpseclib/phpseclib/pull/783, but against 2.0. Commits are cherry picked. No changes from the original PR.
> Switch to extension loaded (2.0)

- phpseclib/Crypt/Random.php
- phpseclib/Math/BigInteger.php
- tests/PhpseclibTestCase.php
- tests/Unit/Math/BigInteger/InternalOpenSSLTest.php
This is pretty different from the other two extension_loaded() PRs. Conceptually, it's pretty similar, but this should be reviewed separately from the other two PRs.
> Switch to extension loaded (1.0)

- .travis.yml
> No longer allow Travis CI to fail on PHP 7.

- phpseclib/Crypt/Hash.php
- tests/Unit/Crypt/HashTest.php
> [master] More work on Hash.php

- phpseclib/Crypt/AES.php
- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/DES.php
- phpseclib/Crypt/RC2.php
- phpseclib/Crypt/RC4.php
- phpseclib/Crypt/Rijndael.php
- phpseclib/Crypt/TripleDES.php
- phpseclib/Crypt/Twofish.php
- tests/Unit/Crypt/AES/TestCase.php
Still need to add unit tests for the new functions..
> Crypt: make it so the key length can be explicitly set and retrieved for all ciphers / 1.0

- phpseclib/Crypt/Random.php
> Update random_bytes() to conform to PHP7.0.0-RC3

- phpseclib/Crypt/RSA.php
- phpseclib/File/X509.php
- tests/Unit/File/X509/CSRTest.php
Fixes #854 . I'll add a unit test later.
> X509: improve base64-encoded detection rules

- phpseclib/Crypt/RSA.php
- tests/Unit/Crypt/RSA/LoadKeyTest.php
> RSA: PKCS8 constant fix for 1.0 branch

- phpseclib/Net/SSH2.php
> Fix PHP invalid index warning

- .travis.yml
> Travis: compile GNU Parallel

- .travis.yml
- phpseclib/File/ASN1.php
- phpseclib/Math/BigInteger.php
- tests/Unit/Math/BigInteger/TestCase.php
- travis/install-php-extensions.sh
If you're using gmp mode for BigInteger var_dump / print_r don't produce very usable output. Also, make a small CS change to ASN1.php.
> small tweaks

- phpseclib/Net/SSH2.php
- tests/Unit/File/ASN1Test.php
- tests/Unit/Net/SSH2Test.php
> update the SSH identifier in the 1.0 branch

- phpseclib/Net/SSH2.php
- tests/Functional/Net/SSH2Test.php
Fixes https://github.com/phpseclib/phpseclib/pull/877#commitcomment-14682005
> SSH2: add isAuthenticated() method for 1.0 branch

- phpseclib/Net/SFTP/Stream.php
- tests/Functional/Net/SFTPStreamTest.php
> SFTP/Stream: fix issue with filenames with hash in them

- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH2.php
- tests/Functional/Net/SFTPStreamTest.php
- tests/Functional/Net/SSH2Test.php
> SFTP/Stream: add support for #'s in filename's

- phpseclib/Crypt/Base.php
- tests/Unit/Crypt/AES/TestCase.php
Fixes #938. Will need to be merged into 2.0 and master branches.
> fix for continuous buffer / CBC / OpenSSL issue for 1.0 branch

- phpseclib/Net/SSH1.php
- phpseclib/Net/SSH2.php
- phpseclib/System/SSH/Agent/Identity.php
#902 changed the default hash algorithm but a few other places needed updating as well.
> SSH: fix broken public key auth in master branch

- composer.json
- composer.lock
- phpseclib/bootstrap.php
> Add bootstrap.php checking environment (MB_OVERLOAD_STRING).

- phpseclib/Net/SSH2.php
- tests/Functional/Net/SFTPUserStoryTest.php
> SSH2: fix for Expected SSH_FXP_ATTRS or SSH_FXP_STATUS error

- phpseclib/Math/BigInteger.php
- tests/Unit/Math/BigInteger/TestCase.php
Added root, pow, max, min, loopforeach functions and tests in BigInteger and applied styleci fixes.
> Added root, pow, max, min, loopforeach in BigInteger

- README.md
- composer.json
> Composer: fix autoloading for 1.0 branch

- tests/bootstrap.php
Ref https://github.com/phpseclib/phpseclib/issues/1048#issuecomment-254190644
Depends on #1050
> Backport tests/bootstrap.php from 2.0 / master onto 1.0.

- phpseclib/File/X509.php
> X509: ignore certificate transparency extension

- README.md
> README: Fix typos.

- phpseclib/File/X509.php
This increases code readability
> Refactor create_function() into anonymous function

- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/RC4.php
> Crypt: fix OpenSSL engine on <= PHP 5.3.6 (2.0 branch)

- phpseclib/Crypt/Blowfish.php
- phpseclib/Crypt/RC4.php
> Crypt: fix OpenSSL engine on <= PHP 5.3.6 (1.0 branch)

- phpseclib/Common/Functions/Objects.php
- phpseclib/File/X509.php
- phpseclib/Math/BigInteger/Engines/PHP.php
- phpseclib/Net/SSH2.php
- tests/Functional/Net/SCPSSH2UserStoryTest.php
- tests/Functional/Net/SFTPStreamTest.php
- tests/Functional/Net/SFTPUserStoryTest.php
- tests/Functional/Net/SSH2AgentTest.php
- tests/Functional/Net/SSH2Test.php
- tests/PhpseclibTestCase.php
- tests/Unit/Crypt/AES/TestCase.php
- tests/Unit/Crypt/BlowfishTest.php
- tests/Unit/Crypt/HashTest.php
- tests/Unit/Crypt/RC2Test.php
- tests/Unit/Crypt/RC4Test.php
- tests/Unit/Crypt/RSA/CreateKeyTest.php
- tests/Unit/Crypt/RSA/LoadKeyTest.php
- tests/Unit/Crypt/RSA/ModeTest.php
- tests/Unit/Crypt/RandomTest.php
- tests/Unit/Crypt/TripleDESTest.php
- tests/Unit/Crypt/TwofishTest.php
- tests/Unit/File/ASN1Test.php
- tests/Unit/File/X509/CSRTest.php
- tests/Unit/File/X509/X509Test.php
- tests/Unit/Net/SSH1Test.php
- tests/Unit/Net/SSH2Test.php
Convert long array() syntax to the short one []
> Long array() to short [] syntax

- phpseclib/Net/SFTP/Stream.php
As described here http://php.net/manual/en/migration70.incompatible.php
> Fix for PHP 7 global variable changes

- phpseclib/Crypt/Common/SymmetricKey.php
- phpseclib/Crypt/RSA.php
- phpseclib/Crypt/Random.php
- phpseclib/File/X509.php
- phpseclib/Math/BigInteger.php
- phpseclib/Math/BigInteger/Engines/BCMath.php
- phpseclib/Math/BigInteger/Engines/BCMath/Base.php
- phpseclib/Math/BigInteger/Engines/PHP.php
- phpseclib/Math/BigInteger/Engines/PHP/Base.php
- phpseclib/Math/BigInteger/Engines/PHP/Reductions/EvalBarrett.php
- phpseclib/Math/BigInteger/Engines/PHP32.php
- phpseclib/Math/BigInteger/Engines/PHP64.php
- phpseclib/Net/SFTP.php
- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH1.php
- phpseclib/Net/SSH2.php
- tests/Functional/Net/SFTPUserStoryTest.php
> Misc. trivial typos

- phpseclib/Crypt/Common/SymmetricKey.php
This could save a lot of your time, and maybe a bit of this library integrity
> Explain the kraken

- README.md
> README: Declare 2.0 branch as LTS. #1310

- phpseclib/Math/BigInteger.php
As composer.json still states it is compatible with 5.3.3
> fix compat with 5.3

- .travis.yml
This can also be applied to the 2.0 branch by merging `1.0` -> `2.0`. `3.0` version at https://github.com/phpseclib/phpseclib/pull/1439.
> [1.0] Updated Travis Config

- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Hash.php
- phpseclib/Crypt/RSA.php
- phpseclib/File/ANSI.php
- phpseclib/File/ASN1.php
- phpseclib/File/X509.php
- phpseclib/Math/BigInteger.php
- phpseclib/Net/SFTP.php
- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH1.php
- phpseclib/Net/SSH2.php
> Fix phpdoc errors reported by Doctum

- phpseclib/Crypt/Base.php
- phpseclib/Crypt/Hash.php
- phpseclib/Crypt/RSA.php
- phpseclib/File/ANSI.php
- phpseclib/File/ASN1.php
- phpseclib/File/X509.php
- phpseclib/Math/BigInteger.php
- phpseclib/Net/SFTP.php
- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH1.php
- phpseclib/Net/SSH2.php
Merge of https://github.com/phpseclib/phpseclib/pull/1514 into 2.x
> Fix phpdoc errors reported by Doctum for 2.x

- phpseclib/Crypt/ChaCha20.php
- phpseclib/Crypt/Common/AsymmetricKey.php
- phpseclib/Crypt/Common/Formats/Keys/PKCS8.php
- phpseclib/Crypt/DSA/Formats/Keys/OpenSSH.php
- phpseclib/Crypt/DSA/Formats/Keys/PKCS1.php
- phpseclib/Crypt/DSA/Formats/Keys/PKCS8.php
- phpseclib/Crypt/Salsa20.php
- phpseclib/Math/BigInteger/Engines/Engine.php
Found using https://travis-ci.com/github/phpseclib/api-docs/builds/184023160#L1223
Nothing major, @bantu maybe you can merge this one ?
Written on master branch, so merging 3.x into master will be fine
> Fix phpdoc issues reported by Doctum

- travis/run-phpunit.sh
and make it relevant, as the change are really needed for phpunit version, not for PHP version
> Simplify test

- phpseclib/Net/SFTP.php
Most of the changes are transparent to the end user. The only differences are that two new functions have been added:
- `setPreferredVersion()`
- `getNegotiatedVersion()`
By default phpseclib will still use SFTPv3 but if it's unavailable it'll use v4/5/6. It'll also use different versions if you tell it to do so via `setPreferredVersion()`.
Maybe I'll change this at some point but right now the SFTPv3 code is battle tested. The SFTPv4/5/6 code is not.
> add SFTP v4/5/6 support to phpseclib v2

- build/psalm_baseline.xml
- phpseclib/Net/SFTP.php
- phpseclib/Net/SFTP/Stream.php
- phpseclib/Net/SSH2.php
> Property typehint in ssh2

- phpseclib/Net/SSH2.php
- tests/Functional/Net/SSH2Test.php
- tests/Unit/Net/SSH2UnitTest.php
Refer to pull request #1888 for details.
> SSH2: Better support for multiple interactive channels & expose shell functions: 3.0 Backport Master Merge

- tests/Unit/Math/PrimeFieldTest.php
> Fix PHP-CS PrimeFieldTest

- phpseclib/Net/SSH2.php
> Fix SSH2::login phpdoc

- phpseclib/Net/SFTP.php
- phpseclib/Net/SSH2.php
- tests/Functional/Net/SSH2Test.php
- tests/Unit/Net/SSH2UnitTest.php
@rposky - since you offered to code review in #1888 I'm @'ing you!
> (3.0 branch) SSH/SFTP: create new openChannel() method to eliminate dupe code

- phpseclib/Exception/InvalidPacketLengthException.php
- phpseclib/Net/SFTP.php
- phpseclib/Net/SSH2.php
- tests/Functional/Net/SSH2Test.php
See original PR #1999, rebased onto 3.0 branch here.
> SSH2: Reorganize get_binary_packet to fetch entire packet before processing

- phpseclib/Net/SSH2.php
> Fix deprecation warning

- phpseclib/Net/SSH2.php
Add a send_eof function similar to:
https://www.php.net/manual/en/function.ssh2-send-eof.php
> Add send_eof function
