phpseclib/phpseclib

phpseclib/File/ASN1.php, tests/Unit/File/ASN1Test.php, tests/Unit/File/X509/CSRTest.php
Fixes #602. The problem was if the attributes SET (context-specific) was included but empty it wasn't being processed correctly.
=> ASN1 / CSR fixes

phpseclib/Crypt/Base.php, phpseclib/Crypt/RC4.php
This PR marks Crypt\Base as abstract as well as the three methods that must be implemented in derived classes. This allows the PHP engine to throw proper errors if derived classes do not implement methods as required by the Base class.
=> Mark Base as abstract

tests/Functional/Net/SFTPUserStoryTest.php, tests/Functional/Net/SSH2Test.php
=> Reenable SSH Functional Test on Travis CI PHP 5.3.3 and below.

phpseclib/Net/SFTP.php
Currently, Net_SCP::put() has a callback parameter, allowing the consumer to monitor/log/report progress (or whatever they please).
This patch adds the same feature, working in the same way, to Net_SFTP::put()
=> Add callback to SFTP.php

phpseclib/Crypt/RSA.php, tests/Unit/Crypt/RSA/LoadKeyTest.php
This adds the function `getPublicKeyFingerprint()` to `Crypt_RSA`:
```php
$rsa = new Crypt_RSA();
$rsa->loadPublicKey(file_get_contents('rsa.pub'));
echo $rsa->getPublicKeyFingerprint('md5');
echo $rsa->getPublicKeyFingerprint('sha256');
```
returns something like
```
c1:b1:30:29:d7:b8:de:6c:97:77:10:d7:46:41:63:87
N9sV2uSNZEe8TITODku0pRI27l+Zk0IY0TrRTw3ozwM
```
Calling this function outputs the same as running `ssh-keygen -lE sha256 f id.pub` or `ssh-keygen -lE md5 -f id.pub`.
The MD5 format is specified in https://tools.ietf.org/html/rfc4716#section-4.
=> RSA: Add support for calculating a public key's fingerprint

README.md, phpseclib/Crypt/RSA.php, phpseclib/Net/SFTP/Stream.php
I ran the code through Code Climate and saw that there were three Boolean comparisons that were not using the identical operator (which is always recommended to avoid unexpected or incorrect results). I updated this to use the identical operator and added the Code Climate badge to the readme.
=> Boolean comparisons was missing an equal sign

phpseclib/Net/SFTP.php, tests/Functional/Net/SFTPUserStoryTest.php
Two new unit tests have been added that show the conditions under which phpseclib failed prior to this commit.
=> SFTP: stat cache updates

phpseclib/Net/SFTP.php, tests/Functional/Net/SFTPUserStoryTest.php
=> SFTP: update conditions under which cache for lstat / . is used for 1.0 branch

phpseclib/File/ASN1.php, phpseclib/File/X509.php, tests/Unit/File/X509/X509Test.php
=> parameter field should be null for RSA keys in X509 certs / fix for 1.0 branch

phpseclib/Net/SFTP/Stream.php, tests/Functional/Net/SFTPLargeFileTest.php, tests/Functional/Net/SFTPStreamTest.php, tests/Functional/Net/SFTPTestCase.php
This reproduces https://github.com/owncloud/core/issues/17027#issuecomment-114929960
The following table was extracted from the description on http://php.net/manual/de/function.fopen.php
```
/*
* mode[0]  create  failOnExists  pos  truncate
*    r        n         n         l       n
*    w        y         n         l       y
*    a        y         n         r       n
*    x        y         y         l       y (implied by create and failOnExists)
*    c        y         n         l       n
*/
```
=> [1.0] Various fixes to fopen mode handling in SFTP Stream

phpseclib/Net/SFTP.php, tests/Functional/Net/SFTPUserStoryTest.php
Fixes #706.
The code change is pretty much the same as the code change in #729 but the unit test is different (pretty much the issue is only an issue when empty directories are being deleted).
=> SFTP: delete stat cache for recursive deletes / 1.0 branch

phpseclib/Net/SSH2.php
=> SSH2: limit the size of data that expect() looks at

phpseclib/File/X509.php
If you re-issue a cert for a website if the serial number isn't different, as well, some browsers may reject the cert. This commit eliminates the need to keep track of serial numbers. It also provides an extra layer of protection to X509 certs per http://crypto.stackexchange.com/q/257/4520
=> X509: use a random serial number for 1.0 branch

phpseclib/Net/SSH2.php
```
+ No more empty for-loop bodies
+ No more counting variables $i leaked into outer context
+ No more unintuitive $i == count(...) comparisons
+ No more array / hash table access of the form $kex_algorithms[$i]
- Function definition, function call overhead.
These are not in the performance critical path, though.
```
Further optimisation probably possible. Unit tests missing. Work in Progress.
=> SSH2: Introduce _array_intersect_first function.

tests/Unit/Math/BigInteger/TestCase.php
Follows #765
Fixes "PHP Warning:  include_once(Math/BigInteger.php): failed to open stream: No such file or directory in [...]/phpseclib/tests/Unit/Math/BigInteger/TestCase.php on line 12" when running without runkit extension.
This was previously required to load MATH_BIGINTEGER_MODE_* constants, but
these are autoloadable via \phpseclib\Math\BigInteger::MODE_* now and the
include path was removed.
=> Remove include statement from BigInteger TestCase.

tests/PhpseclibTestCase.php
Follows #773
Fixes "PHP Warning:  runkit_import(Math/BigInteger.php): failed to open stream: No such file or directory in /home/travis/build/phpseclib/phpseclib/tests/PhpseclibTestCase.php on line 97" as for example seen in https://travis-ci.org/phpseclib/phpseclib/jobs/75492795
=> Make paths to runkit_import() absolute due to lack of include path.

.travis.yml
.scrutinizer.yml no longer exists
=> .travis.yml: Remove outdated comment about .scrutinizer.yml

phpseclib/Net/SFTP/Stream.php, phpseclib/Net/SSH2.php, tests/Functional/Net/SFTPStreamTest.php, tests/Functional/Net/SFTPTestCase.php, tests/Unit/Net/SSH2Test.php
Refactoring that was discussed in #786
=> Connection reuse refactoring to rid of globals

phpseclib/Net/SSH1.php
I took a stab at replicating the SSHv2 exception support from #739 into SSHv1. As they are somewhat different, I targeted the user_error() calls for replacement, however some additional return false; statements may warrant a runtime exception?
Just as with the other exception support, the target is master and not 1.0 or 2.0. Please let me know the changes you would like me to make prior to accepting this PR.
=> Exception support for SSHv1

phpseclib/Crypt/Random.php, phpseclib/Math/BigInteger.php
`public static function` is replaced with `static function` in Random.php for reasons described at https://github.com/phpseclib/phpseclib/pull/813#commitcomment-13197976
I also removed an unnecessary `break`. This `break` isn't present in the 1.0 branch:
https://github.com/phpseclib/phpseclib/blob/1.0/phpseclib/Math/BigInteger.php#L322
=> small CS changes

phpseclib/Math/BigInteger.php
`$x = gmp_init(6); empty($x);` demonstrates the problem
=> BigInteger: fix PHP7 error

phpseclib/Crypt/RSA.php, phpseclib/File/X509.php, phpseclib/Net/SSH1.php, phpseclib/Net/SSH2.php, phpseclib/System/SSH/Agent.php, tests/Unit/Crypt/RSA/CreateKeyTest.php, tests/Unit/Crypt/RSA/LoadKeyTest.php, tests/Unit/Crypt/RSA/ModeTest.php, tests/Unit/File/X509/SPKACTest.php, tests/Unit/File/X509/X509Test.php
Replaces #815. I renamed loadKey to load to make RSA have an API more similar to the API I have planned for X509 (and CSR and SPKAC and all the classes I plan to split X509 up into).
Next step for RSA: splitting out all the key format handling stuff into their own individual class files.
=> RSA: make createKey static and make it return RSA objects

phpseclib/Net/SFTP.php, tests/Functional/Net/SFTPUserStoryTest.php
Replaces #830.
#830 is for the master branch but the issue is present in the 1.0 branch as well. I've also added a unit test that demonstrates the issue.
=> SFTP.php : prevent endless loop when upload completed with non-zero $start or $local_start for 1.0

phpseclib/Crypt/AES.php, phpseclib/Crypt/Base.php, phpseclib/Crypt/Blowfish.php, phpseclib/Crypt/DES.php, phpseclib/Crypt/Hash.php, phpseclib/Crypt/RC2.php, phpseclib/Crypt/RC4.php, phpseclib/Crypt/RSA.php, phpseclib/Crypt/Rijndael.php, phpseclib/Crypt/TripleDES.php, phpseclib/Crypt/Twofish.php, phpseclib/File/ASN1.php, phpseclib/File/X509.php, phpseclib/Math/BigInteger.php, phpseclib/Net/SCP.php, phpseclib/Net/SFTP.php, phpseclib/Net/SSH1.php, phpseclib/Net/SSH2.php, phpseclib/System/SSH/Agent.php
A lot of the in-line comments for #827 had to do with the phpDoc syntax so this makes all current phpDoc calls consistent.
It also adds missing @return statements to four functions in Crypt/RSA.php.
=> phpDoc changes for 1.0 branch

phpseclib/Net/SFTP.php, tests/Functional/Net/SFTPUserStoryTest.php
=> Fix SFTP::chmod not using realpath on the filepath

tests/Unit/File/ASN1Test.php
=> Correct indentation on pvno array definition.

phpseclib/Crypt/RSA.php
Fixes #879 for 2.0 branch
This was fixed with #866 but I guess that commit got overwritten with a bad merge.
I note that #866 had a ton of extra commits. My guess is that did `git checkout -b rsa-pkcs8-fix-2.0` while in `rsa-pkcs8-fix-1.0` and then merged `2.0` into `rsa-pkcs8-fix-2.0`, instead of the other way around. That still doesn't explain why the commit just disappeared but it would explain all the extra commits in #866.
=> RSA: fix PKCS8 key handling (again)

phpseclib/Crypt/RSA.php, phpseclib/File/X509.php, phpseclib/Net/SSH1.php, phpseclib/Net/SSH2.php, phpseclib/System/SSH/Agent/Identity.php, tests/Unit/Crypt/RSA/CreateKeyTest.php, tests/Unit/Crypt/RSA/ModeTest.php
- setEncryptionMode() / setSignatureMode() methods have been removed.
instead you'll do `$rsa->verify($message, $signature, RSA::PADDING_PKCS1)` or whatever. the defaults remain the same as before. ie. `$rsa->verify($message, $signature)` still does PSS signatures (altho it now does them with sha256 for the hash and MGF). i thought about making it so that `$rsa->verify($message, $signature)` would try both `RSA::PADDING_PSS` and `RSA_PADDING_PKCS` in the same way that RSA.php brute forces key formats but decided against it. the reason being that a lot of the success of `verify()` and `decrypt()` depend on the hash algorithms being used and i don't want to brute force those as well.
- added a new signature verification mode - RSA::PADDING_RELAXED_PKCS1.
in rare cases it might succeed where …
=> RSA: changes to how encryption / signatures work

phpseclib/Crypt/RSA.php, phpseclib/Math/BigInteger.php, phpseclib/Net/SSH2.php, tests/Unit/Math/BigInteger/TestCase.php
This PR does the following:
- replace `$x->copy()` with `clone $x` and rm the `copy()` method
- makes a bunch of private methods static and makes `random()` and `randomPrime()` static.
in so doing this PR resolves #568
- adds type hinting to public methods
=> BigInteger: make select methods static, add type hinting, etc

phpseclib/Crypt/Base.php, phpseclib/Crypt/RSA/PuTTY.php, tests/Unit/Crypt/AES/TestCase.php, tests/Unit/Crypt/BlowfishTest.php, tests/Unit/Crypt/DESTest.php, tests/Unit/Crypt/RC2Test.php, tests/Unit/Crypt/TripleDESTest.php, tests/Unit/Crypt/TwofishTest.php
See https://github.com/phpseclib/phpseclib/issues/907#issuecomment-168563911.
Note that IV's and keys are still null padded if they're not long enough. Perhaps it ought not be doing this, either, but, none-the-less, this behavior is consistent with OpenSSL and mcrypt. I'm not opposed to changing that behavior, either, but that'll be another commit for another day.
That said, w.r.t. throwing exceptions if IV's aren't long enough...  the necessity for that is going to be somewhat mode dependent. In CTR mode I'm not sure that kind of behavior is optimal. ie. in CBC mode the IV depends on the encryption result of the last block. But in CTR mode it doesn't. In CTR mode you just increment the IV by one in each block. Ideally, you'd generate the IV by doing something like `random_string(32)` but …
=> Crypt/Base: throw an exception if an IV is required but not defined

phpseclib/Crypt/RSA.php, tests/Unit/Crypt/RSA/ModeTest.php
Currently, when you pass a string longer than the modulo to either encrypt or decrypt phpseclib splits the message up into smaller chunks and encrypts each chunk. I still stand by it as being a perfectly valid thing to be doing (see https://github.com/phpseclib/phpseclib/issues/135#issuecomment-21660586). Further, I think it's kinda the "PHP way" to silently deal with errors. But, that said, if I'm going to be [throwing IVs when none are provided](https://github.com/phpseclib/phpseclib/issues/907#issuecomment-168563911) (instead of using a "null string"), then maybe other "silent errors" ought to be handled differently as well.
For BC purposes the 1.0 and 2.0 branches will never do this.
(I was reminded of this by considering whether or not the `\LengthException` thrown in `encrypt` ought …
=> RSA: error out when encrypting strings that are too long

phpseclib/Crypt/AES.php, phpseclib/Crypt/Base.php, phpseclib/Crypt/Blowfish.php, phpseclib/Crypt/DES.php, phpseclib/Crypt/RC2.php, phpseclib/Crypt/RC4.php, phpseclib/Crypt/RSA.php, phpseclib/Crypt/Random.php, phpseclib/Crypt/Rijndael.php, phpseclib/Crypt/TripleDES.php, phpseclib/Crypt/Twofish.php, phpseclib/File/X509.php, phpseclib/Net/SCP.php, phpseclib/Net/SFTP.php
As per https://github.com/phpseclib/phpseclib/pull/928#issuecomment-173621562: Taking over the `use` operator usage clean-up to the 2.0 branch:
1. Cherry-picked c9a80ff748d6b64a66cb3fc20db4608305279af2 to the 2.0 branch and resolved conflicts.
2. Checked if other files of the 2.0 branch are affected - none found.
=> Taking over cleanup of `use` operator usage to the 2.0 branch

phpseclib/Crypt/AES.php, phpseclib/Crypt/Base.php, phpseclib/Crypt/Blowfish.php, phpseclib/Crypt/DES.php, phpseclib/Crypt/RC2.php, phpseclib/Crypt/RC4.php, phpseclib/Crypt/RSA.php, phpseclib/Crypt/RSA/PKCS.php, phpseclib/Crypt/RSA/PKCS1.php, phpseclib/Crypt/RSA/PKCS8.php, phpseclib/Crypt/RSA/PuTTY.php, phpseclib/Crypt/Random.php, phpseclib/Crypt/Rijndael.php, phpseclib/Crypt/TripleDES.php, phpseclib/Crypt/Twofish.php, phpseclib/File/X509.php, phpseclib/Net/SCP.php, phpseclib/Net/SFTP.php, phpseclib/System/SSH/Agent.php, phpseclib/System/SSH/Agent/Identity.php
This does the following:
1. Removes superfluous usage of the `use` operator. Specifically, that operator is not needed to use classes in the same `namespace` (see https://secure.php.net/manual/en/language.namespaces.rules.php). E.g.:
```php
namespace some\namespace;
use some\namespace\SomeClass; // this is not needed
class MyClass
{
$a = new SomeClass;
}
```
It would only be needed, if "aliasing" was used (see https://secure.php.net/manual/en/language.namespaces.importing.php), e.g.:
```php
namespace some\namespace;
use some\other\namespace\SomeClass;
use some\namespace\SomeClass as MySomeClass; // aliased due to name clash (e.g. introduced at a later time, aliased to not have to adapt the code if aliasing the above class instead)
class MyClass
{
$a = new SomeClass;    // this is …
```
=> Cleanup of `use` operator usage

phpseclib/File/X509.php, tests/Unit/File/X509/X509Test.php
Switched out pack/unpack and ip2long/long2ip with inet_pton/ntop for ipv6 encoding support in x509v3 subject alternative names. The functions should be in PHP5.1 (or 5.3 for Windows) or later.
I am attaching my before and after certificates generated with this patch for comparison.
[ipv6.before.crt.txt](https://github.com/phpseclib/phpseclib/files/105873/ipv6.before.crt.txt)
[ipv6.after.crt.txt](https://github.com/phpseclib/phpseclib/files/105872/ipv6.after.crt.txt)
Please let me know if this is acceptable, or if there are changes / alternative approaches you would prefer. Thanks.
=> IPv6 support for X509v3 SubjectAltNames

phpseclib/Net/SSH2.php
PECL Libsodium 1.0.x uses `\Sodium\function_name` instead of `\Sodium::method_name`.
https://paragonie.com/book/pecl-libsodium/read/03-utilities-helpers.md#version
=> Correct Sodium check

phpseclib/Net/SFTP.php
This may be completely wrong implementation, but it worked in my tests. It sped up the download from ~400 Kb/s to ~12 Mb/s.
=> Implement parallel download

phpseclib/Crypt/RSA.php
using unset causes an error in $this->load():
Undefined property: phpseclib\Crypt\RSA::$publicExponent in phpseclib/phpseclib/Crypt/RSA.php on line 709
=> set publicExponent to false instead of unsetting

phpseclib/Crypt/Base.php, phpseclib/Crypt/RSA.php, phpseclib/Crypt/RSA/MSBLOB.php, phpseclib/Crypt/RSA/PKCS.php, phpseclib/Crypt/RSA/PKCS1.php, phpseclib/Crypt/RSA/PKCS8.php, phpseclib/Crypt/RSA/PuTTY.php, phpseclib/Crypt/Random.php, phpseclib/Math/BigInteger.php, phpseclib/Net/SSH1.php
- Hex::decode('aabb') can be replaced with "\xaa\xbb"
- Hex::decode(sha1('...')) can be replaced with sha1('...', true)
=> remove a few calls to paragonie/constant_time_encoding

phpseclib/Crypt/RSA.php, tests/Unit/Crypt/RSA/LoadKeyTest.php
=> RSA: don't attempt to use the CRT when zero value components exist

phpseclib/File/X509.php
All major browsers will stop to accept certificates that use SHA1 by 2017 (see https://en.wikipedia.org/wiki/SHA-1). So at least SHA256 should be the default now.
=> Change default signature algorithm from SHA1 to SHA256

phpseclib/Crypt/Hash.php, tests/Unit/Crypt/HashTest.php
The motivation for this PR is as follows:
https://github.com/phpseclib/phpseclib/pull/956#issuecomment-209115492
=> Hash: throw exceptions if hash isn't explicitly supported

.travis.yml, phpseclib/Crypt/Base.php, phpseclib/Crypt/RC2.php, travis/run-phpunit.sh
PHP 7.1 deprecated mcrypt per https://wiki.php.net/rfc/mcrypt-viking-funeral but mcrypt is still, none-the-less, useful for phpseclib because of deficiencies in the OpenSSL bindings PHP has.
Among other things, OpenSSL does not persist the state from function call to function call. So if you call encrypt('plaintext') twice, with the same plaintext, you'll get the same ciphertext each time. This is not how SSH operates or how phpseclib operates when you're in continuous mode. phpseclib is able to emulate state persistence with OpenSSL with block ciphers but it can't do this with stream ciphers like RC4.
Further, SSH / phpseclib support ciphers like arcfour256, which is RC4 with a 256-bit key. OpenSSL only supports RC4 with 40-bit, 64-bit and 128-bit keys (called rc4-40, rc4-64 and rc4 in …
=> remove E_DEPRECATED notices from PHP 7.1

phpseclib/Net/SCP.php, phpseclib/Net/SFTP.php, phpseclib/Net/SSH1.php, phpseclib/Net/SSH2.php
This changes suppresses the "not enough input" errors that phpseclib can emit.
The specific motivation for this was #1046 (scroll towards the bottom).
=> suppress unpack() PHP warnings

phpseclib/Net/SSH2.php
=> SSH2: make it so disabling PTY closes exec() channel if it's open

phpseclib/File/X509.php
It would seem that issue https://github.com/phpseclib/phpseclib/issues/1103 array_map would prefer a fully qualified namespace.
=> namespacing the array_map function

phpseclib/Crypt/Common/SymmetricKey.php
Fix wrong DocComment annotation of return type declaration.
I'm new to this phseclib project. so I'm not sure if it's correct, but it seems there are many wrong DocComment annotations inconsistents with access modifier of php syntax (public / protected / private).
Must I wrote some patches to fix these wrong DocComment, or just my lack of understanding about this code base?
=> Fix wrong doccomment annotation of return type

phpseclib/Math/BigInteger.php, tests/Unit/Math/BigIntegerTest.php
If you dont have gmp extension installed, you are not able to use BigInteger class because of the BadConfigurationException.
=> Fix BigInteger BadConfigurationException

phpseclib/Crypt/Common/SymmetricKey.php, tests/Unit/Crypt/AES/TestCase.php
This patch add 'cfb8' cipher mode of operation to SymmetricKey class.
This mode was intended to be used with AES128 (Rijndael) encryption.
This patch supports the engines as foollows
* OpenSSL
* mcrypt
* Eval
* PHP
**Becase I NEED!**
mcrypt extension is planned to be removed from next release of php version 7.2. And I have some codebase which requires AES-128-CFB8 with mcrypt extension. So, I need to replace the code with mcrypt compatible 'cfb8' mode encryption / decryption library. And phpseclib has internal PHP / Eval engine.
```php
<?php
use phpseclib\Crypt\AES;
$key = "VpwGPQ33RrgiEmMV";
$msg = "this is secret message";
$aes = new AES("CFB8");
$aes->enableContinuousBuffer();
$aes->setKey($key);
$aes->setIV($key);
$cipher = $aes->encrypt($msg);
$actual = $aes->decrypt($cipher); …
```
=> Add 'cfb8' cipher mode of operation support

phpseclib/Crypt/Common/SymmetricKey.php
Fix wrong doccomment annotations.
It seems type of first argument of constructor and `setPreferredEngine()` method was changed by the commit 4171262b9
But I would rather wish I can use constants integer value like before.
May I wrote patch which accepts constants value in addition like below?
```php
<?php /* file: phpseclib/Crypt/Common/SymmetricKey.php */
/**
* Default constructor
* @param int|string $mode name of mode as string or constant integer value
* @access public
* @throws \InvalidArgumentException if an invalid / unsupported mode is provided
*/
public function __construct($mode)
{
if (is_string($mode)) {
$mode = strtolower($mode);
// necessary because of 5.6 compatability; we can't do isset(self::MODE_MAP[$mode]) in 5.6
$map = self::MODE_MAP;
if (!isset($map[$mode])) {
throw new …
```
=> Fix wrong doccomment annotation and Suggestion

phpseclib/Net/SFTP.php
From SFTP servers that are configured in a way this library can't handle we should show the unexpected value we receive when it doesn't correspond to one of the constants we expect.
This PR adds the missing information to all the related exceptions in SFTP handling.
_Made with :heart: from @comsolit, Switzerland._ :smiley:
=> Unveil received value in unexpected value exceptions (SFTP)

tests/Functional/Net/SCPSSH2UserStoryTest.php, tests/Functional/Net/SFTPStreamTest.php, tests/Functional/Net/SFTPUserStoryTest.php, tests/Functional/Net/SSH2Test.php, tests/Unit/File/ANSITest.php
I've refactored some tests, using:
- `assertInternalType` instead of `is_*` functions;
- `assertContains` instead of `in_array` function;
- `assertCount` instead of `count` function.
=> Refactoring tests

phpseclib/Crypt/RSA.php, phpseclib/Math/BigInteger.php
Fixes an issue I raised at https://github.com/phpseclib/phpseclib/issues/1255
Proof of logic at https://3v4l.org/RqrHt
I ended up moving more code than discussed in the issue - initially to avoid `$content` being undefined when it came to `preg_match_all()`, but also as it made sense grouping the code that way. Also, initialising `$versions` outside the check, right at the start ensures it's always defined for the `switch` code further down.
=> Check phpinfo() is available before using

phpseclib/Crypt/Base.php, tests/Unit/Crypt/AES/TestCase.php
I need CFB8 in one of my projects but I’d rather not rely on an unstable API just for that, so I backported the changes from #1192 to the 2.0 branch.
=> Backport CFB8 support from master to 2.0

phpseclib/Crypt/RSA.php
There seems to be a *lot* of invalid docblock annotations but I just wanted to fix a few that were affecting me whilst using some RSA features.
=> Fixed some RSA docblock types

README.md
According to https://getcomposer.org/doc/03-cli.md#require
=> Fix composer require syntax in readme

phpseclib/Common/Functions/Strings.php, phpseclib/Crypt/AES.php, phpseclib/Crypt/Common/SymmetricKey.php, phpseclib/Math/BinaryField.php, phpseclib/Math/BinaryField/Integer.php, phpseclib/Net/SSH2.php, tests/Unit/Crypt/GCMTest.php
[GCM](https://en.wikipedia.org/wiki/Galois/Counter_Mode) is an authenticated encryption mode most commonly used with AES but that can, in fact, be used with any block cipher with a block size of 128 bits. Here's how it's used:
Encrypting:
```php
$aes = new AES('gcm');
$aes->setKey(str_repeat('x', 16));
$aes->setNonce(str_repeat('x', 12));
$aes->setAAD('whatever'); // optional; can be of any length
$ciphertext = $aes->encrypt('...');
$tag = $aes->getTag(); // can optionally pass the length of the tag as a parameter; can be between 4-16 bytes
```
Decrypting:
```php
$aes = new AES('gcm');
$aes->setKey(str_repeat('x', 16));
$aes->setNonce(str_repeat('x', 12));
$aes->setAAD('whatever'); // optional; can be of any length
$plaintext = $aes->decrypt('...'); // throws an exception if the …
```
=> add support for Galois/Counter Mode (GCM)

phpseclib/Crypt/RSA.php
My static analyzer failed due to this type hint. I did notice it was already corrected in the master branch.
=> Fixed RSA loadKey type hint

phpseclib/Crypt/ChaCha20.php, phpseclib/Crypt/Common/SymmetricKey.php, phpseclib/Crypt/RC4.php, phpseclib/Crypt/Salsa20.php, phpseclib/Net/SSH2.php, tests/Unit/Crypt/ChaCha20.php, tests/Unit/Crypt/Salsa20.php
This addresses #396 / #397.
Here's an example of how to use it:
```php
$c = new ChaCha20;
$c->setKey('...');
$c->setNonce('...');
//$c->setCounter(...);
echo bin2hex($c->encrypt('...'));
```
Note how it uses `setNonce()` instead of `setIV()`.
Poly1305 can be enabled by either doing `$c->enablePoly1305();` (at which point the key is auto-determined using the AEAD construction described in [RFC8439](https://tools.ietf.org/html/rfc8439#section-2.8)) or `$c->setPoly1305Key('...');` (the latter is necessary for SSH's use of ChaCha20-Poly1305).
AAD's can be set by doing `$c->setAAD()` and the tag can be set (for verification during decryption) by doing `$c->setTag()`. To retrieve the tag after encryption you'd do `$c->getTag()`.
=> add Salsa20 / ChaCha20 / Poly1305 support

phpseclib/Crypt/Blowfish.php, phpseclib/Crypt/Common/SymmetricKey.php, phpseclib/Crypt/DES.php, phpseclib/Crypt/RC2.php, phpseclib/Crypt/Rijndael.php, phpseclib/Crypt/TripleDES.php, phpseclib/Crypt/Twofish.php
Addresses findings brought up in #1396. Ciphers extending the base SymmetricKey class expect integers in their constructor param and checks, but then pass the given value to the inherited constructor that expects string labels. This leads to a case where either the check, or the inherited mapper, can't function.
This PR addresses that by changing the SymmetricKey to accept both strings and the constants themselves, and fixes execution order; the inherited mapper is ran before the validation check so that it will function if a label is given instead of the constant's value.
Fixes #1396
=> Fix SymmetricKey and cipher class constructor mode types, and mapping execution order

phpseclib/Crypt/Hash.php, phpseclib/Net/SSH2.php, tests/Unit/Crypt/HashTest.php
This commit adds support for umac-64 and umac-128 to SSH2.php and also support for the EtM methods.
Once this commit is merged I figure I'll create a 3.0 tag. I'll then commence work on revamped documentation in preparation for a 3.0.0 release.
=> add new HMAC algorithms

phpseclib/Net/SSH2.php
Suppressing errors from stream_select() makes debugging timeouts extremely hard.
=> Remove error suppression from stream_select()

phpseclib/Crypt/RSA.php
If you try to use `setKey` with a non supported type, you handle with an exception.
Indeed the method `_parseKey` will return `null` but the check made after is `=== false`.
This fix, should be made in 2.0 too. I assume you'll merge 1.0 into 2.0.
=> _parseKey should return false by default

phpseclib/Net/SSH2.php
Hi,
I am testing my latest version on different code-bases and I found one error:
```
------ ----------------------------------------------------------------------------------------------------------- 
Line   /mnt/Dev/@code-lts/@doctum-fork/api-docs/phpseclib/phpseclib/Net/SSH2.php                                  
------ ----------------------------------------------------------------------------------------------------------- 
2711   The "interval" parameter of the method "setKeepAlive" is missing a @param tag on "Net_SSH2::setKeepAlive"  
------ ----------------------------------------------------------------------------------------------------------- 
[ERROR] Found 1 error                                                                                                  
```
Affects: …
=> Fix a Doctum 5.3.0-dev phpdoc reported error

phpseclib/File/X509.php
While the method intents to support date objects, it's actually made impossible due to `strtolower()` throwing an error. This preliminary check will actually allow to enter into the `else` without triggering the `if (!is_object($date) || !($date instanceof DateTimeInterface))` e.g. support `DateTimeInterface` as parameter.
=> Allow to pass end date as DateTime

phpseclib/Net/SFTP.php
Most of the changes are transparent to the end user. The only differences are that two new functions have been added:
- `setPreferredVersion()`
- `getNegotiatedVersion()`
By default phpseclib will still use SFTPv3 but if it's unavailable it'll use v4/5/6. It'll also use different versions if you tell it to do so via `setPreferredVersion()`.
Maybe I'll change this at some point but right now the SFTPv3 code is battle tested. The SFTPv4/5/6 code is not.
=> add SFTP v4/5/6 support to phpseclib v1

phpseclib/Common/Functions/Strings.php, phpseclib/Net/SFTP.php, phpseclib/Net/SSH2.php
Most of the changes are transparent to the end user. The only differences are that two new functions have been added:
- `setPreferredVersion()`
- `getNegotiatedVersion()`
By default phpseclib will still use SFTPv3 but if it's unavailable it'll use v4/5/6. It'll also use different versions if you tell it to do so via `setPreferredVersion()`.
Maybe I'll change this at some point but right now the SFTPv3 code is battle tested. The SFTPv4/5/6 code is not.
=> add SFTP v4/5/6 support to phpseclib v3

phpseclib/Net/SSH2.php
Fixes https://github.com/phpseclib/phpseclib/issues/1721 for the 2.0 branch
=> Remove define() from SSH2 and use class constants instead (2.0 branch)

phpseclib/Net/SSH2.php
Fixes https://github.com/phpseclib/phpseclib/issues/1721 for the 3.0 branch
=> Remove define() from SSH2 and use class constants instead (3.0 branch)

phpseclib/Net/SSH2.php
Fixes https://github.com/phpseclib/phpseclib/issues/1721 for the master branch
=> Remove define() from SSH2 and use class constants instead (master branch)

phpseclib/Crypt/RSA.php, phpseclib/Math/BigInteger.php
I've come across two users whose web hosting disables the function `phpinfo()` (see: https://wordpress.org/support/topic/php-fatal-error-on-connection-attempt/). This is used in phpseclib 1.0 (which we still have to use, because as a backup plugin, we want to support users who are backing up their antique WordPress sites before they test upgrading them).
This PR checks that `phpinfo()` is available before using it, avoiding a resulting PHP fatal error.
=> Don't use phpinfo() if it is disabled

phpseclib/Net/SSH2.php, tests/Unit/Net/SSH2UnitTest.php
Just an added nicety for callers configuring timeouts, and allowing callers to respect default client timeout configuration without themselves hard-coding to the 10-second value presently applied on __construct().
=> SSH2: Adding getter for timeout

README.md
The current link leads to the repository:
> [![CI Status](https://github.com/phpseclib/phpseclib/actions/workflows/ci.yml/badge.svg?branch=master&event=push "CI Status")](https://github.com/phpseclib/phpseclib)
The new link leads to the results of the CI:
> [![CI Status](https://github.com/phpseclib/phpseclib/actions/workflows/ci.yml/badge.svg?branch=master&event=push "CI Status")](https://github.com/phpseclib/phpseclib/actions/workflows/ci.yml?query=branch%3Amaster)
=> README: link on CI badge leads to the results

phpseclib/Net/SSH2.php, tests/Functional/Net/SSH2Test.php, tests/Unit/Net/SSH2UnitTest.php
Refer to pull request #1888 for details.
=> SSH2: Better support for multiple interactive channels & expose shell functions: 3.0 Backport

phpseclib/Net/SSH2.php
`fputs()` can return `int|false`.  if it fails and `$sent` is `false`, then our exception message looks a little confusing:
> Only   of XXX bytes were sent
This change updates the message to be more descriptive if the `fputs()` fails.
> Unable to write XXX bytes
=> (3.0 branch) update exception message

phpseclib/bootstrap.php
If "jit" is not defined in $status array, it generates an "Undefined index: jit" notice.
=> Fix Undefined index jit notice

phpseclib/Math/BigInteger.php, phpseclib/Math/BigInteger/Engines/PHP.php, phpseclib/Math/BigInteger/Engines/PHP32.php, phpseclib/Math/BigInteger/Engines/PHP64.php, phpseclib/bootstrap.php
This fixes static analysis with Psalm v5 (which enables JIT by default) of projects which require phpseclib as a dependency.
=> Move JIT check to BigInteger

phpseclib/Net/SSH2.php
Fatal error: Uncaught Error: Cannot access property phpseclib3\Net\SFTP::$disconnect_reasons was being received when login failed. 
changing static:: to self:: fixed the issue
=> access $disconnect_reasons using self instead of static

phpseclib/Crypt/Base.php, phpseclib/Crypt/Hash.php
For security reasons, it appears that some hosting providers have decided to disable `php_uname` function, unfortunately this has led to a PHP fatal error when the function gets called without first checking its existence. We'd like to propose changes in the `/Crypt/Base.php` and `Crypt/Hash.php` which is to use `function_exists()` to check the `php_uname` existence.
=> Undefined php_uname function due to hosting restriction

phpseclib/Crypt/Common/AsymmetricKey.php, phpseclib/Crypt/Common/Formats/Keys/PKCS8.php, phpseclib/Crypt/Common/SymmetricKey.php, phpseclib/Crypt/EC.php, phpseclib/Crypt/EC/Formats/Keys/XML.php, phpseclib/File/X509.php, phpseclib/Math/BinaryField.php, phpseclib/Math/PrimeField/Integer.php, phpseclib/Net/SFTP.php, phpseclib/Net/SSH2.php, tests/PhpseclibFunctionalTestCase.php
Fixes all issues that emit deprecation notices on PHP 8.4 for implicit nullable parameter type declarations.
See:
- [RFC](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types)
- [PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)
=> [PHP 8.4] Fixes for implicit nullability deprecation

phpseclib/Crypt/EC/Formats/Keys/PKCS8.php, tests/Unit/Crypt/EC/KeyTest.php
This is the second attempt at a PR for Ed448 private key support in PKCS#8 format against 3.0 branch (original PR: [2000](https://github.com/phpseclib/phpseclib/pull/2000) )
- Fixes parsing of Ed448 private keys in PKCS#8 format (`PKCS8.loadEdDSA()`)
- Fixes exporting of Ed448 private keys in PKCS#8 format (`PKCS8.savePrivateKey()`)
- Adds unittests `testEd448PublicKey()` and `testEd448PrivateKey()`
I tried to retain the original coding style, so the if/else structure will assume Ed448 if the curve is not Ed25519 (which mimics the ternary operator that was there before this patch), it would be cleaner to refactor this to a switch statement in the future.
Also, I'd recommend adding a proper wrapper for an ASN.1 `OCTET STRING`, instead relying on the hardcoded `\x04\x20` and `\x04\x39`.
In …
=> Fix support for Ed448 private keys in PKCS#8 format

phpseclib/Net/SSH2.php
instead of $stop - $start use the defined $elapsed var as the var $stop isn't set.
It gives errors and our log is filling with this trival var.
=> instead of $stop - $start use the defined $elapsed var

phpseclib/Net/SSH2.php
fix #2010 back-ported  for master from the 3.0 branch . As the 3.0 branch is different then the master branch
=> fix #2010 back-ported for master of phpseclib

phpseclib/Net/SSH2.php, tests/Functional/Net/SSH2Test.php, tests/PhpseclibTestCase.php, tests/Unit/Net/SSH2UnitTest.php
Looks like I got sloppy around the keep alive changes, w.r.t. #2009, #2010, #2011. Sorry about that!
I see it's still not quite right though, as we're basing the stream timeout on time since the last read as opposed to time remaining in the keep alive interval. This attempts to fix that along with adding a counter for packet read time and ensuring that `last_packet` is always incremented, even if logging is not enabled.
=> Correction to stream timeout for keep alive

phpseclib/Exception/TimeoutException.php, phpseclib/Net/SFTP.php, phpseclib/Net/SSH2.php, tests/Unit/Net/SSH2UnitTest.php
This is meant to address #2014 and is a follow-on to #2006, which modified the contract of `get_binary_packet` when timeout events occur (now returning `true` where previously either `true` or a `ConnectionClosedException` would be thrown).
With this change, `get_binary_packet` is modified to always return a `string` representing the next packet or to throw an exception in the event that it cannot. A new `TimeoutException` is introduced and thrown in the respective event while waiting for the next packet.
In order to maintain current behavior of most callers of `get_binary_packet`, a helper `get_binary_packet_or_close` is introduced which handles timeout exceptions by closing the connection and throwing a `ConnectionClosedException` instead. This helper also enables callers to set a …
=> SSH2: Consolidate get_binary_packet error handling

phpseclib/Net/SSH2.php, tests/Unit/Net/SSH2UnitTest.php
Attempting to address #2020, this issue formalizes the implied behavior prior to #1999 regarding PHP stream timeouts, by defaulting to PHP's `default_socket_timeout` for stream read functions when the user has not requested a timeout or keep-alive interval. This change mirrors the default timeout behavior of PHP socket streams, as evidenced [here](https://github.com/php/php-src/blob/master/main/streams/xp_socket.c#L964), and thus the behavior prior to #1999 changes, when `stream_set_timeout` was conditionally invoked. It is noteworthy that the prior implementation would not permit an update to remove a timeout via `SSH2:setTimeout`, given the conditional invocation of `stream_set_timeout`, now supported.
The following simple test confirms the underlying use of the default socket timeout …
=> SSH2: Defer to default socket timeout in absence of more specific value

phpseclib/Net/SSH2.php, tests/Unit/Net/SSH2UnitTest.php
This attempts to address #2030 where it was reported the potential to enter an infinite loop while disconnecting, seemingly due to an absent check for a closed/eof socket prior to issuing a final DISCONNECT message. This change prevents sending said DISCONNECT message on a closed socket, and also adds further protection for looping for other possible error paths.
=> Prevent loops during disconnect

phpseclib/Common/Functions/Strings.php, phpseclib/Crypt/Common/Formats/Keys/PKCS8.php, phpseclib/Crypt/Common/Formats/Keys/PuTTY.php, phpseclib/Crypt/DSA/Formats/Keys/PuTTY.php, phpseclib/Crypt/DSA/PrivateKey.php, phpseclib/Crypt/DSA/PublicKey.php, phpseclib/Crypt/EC/PrivateKey.php, phpseclib/Crypt/EC/PublicKey.php, phpseclib/Crypt/RSA.php, phpseclib/Crypt/RSA/Formats/Keys/MSBLOB.php, phpseclib/Crypt/RSA/Formats/Keys/PuTTY.php, phpseclib/File/ASN1.php, phpseclib/File/X509.php, phpseclib/Math/BigInteger.php, phpseclib/Math/BigInteger/Engines/BCMath.php, phpseclib/Math/BigInteger/Engines/BCMath/Reductions/Barrett.php, phpseclib/Math/BigInteger/Engines/Engine.php, phpseclib/Math/BigInteger/Engines/GMP.php, phpseclib/Math/BigInteger/Engines/PHP/Reductions/Barrett.php, phpseclib/Net/SFTP.php, phpseclib/Net/SFTP/Stream.php, phpseclib/Net/SSH2.php
This PR applies the recommended changes by Fortify to remediate the `Possible Variable Overwrite: Global Scope` vulnerability.
> Invoke extract(array $var_array [, int $extract_type [, string $prefix]]) with the second argument set to EXTR_SKIP, which prevents the function from overwriting global variables that are already defined.
CWE ID: 473
This was previously discussed on #2021 .
=> Fix - Possible Variable Overwrite: Global Scope

phpseclib/File/X509.php
Deprecated: phpseclib3\File\X509::getRequestedCertificateExtensions(): Implicitly marking parameter $csr as nullable is deprecated, the explicit nullable type must be used instead
fixed this for PHP8.4
=> fix deprecated

phpseclib/Common/Functions/Strings.php, phpseclib/Crypt/Common/Formats/Keys/PKCS8.php, phpseclib/Crypt/Common/Formats/Keys/PuTTY.php, phpseclib/Crypt/DSA/Formats/Keys/PuTTY.php, phpseclib/Crypt/DSA/PrivateKey.php, phpseclib/Crypt/DSA/PublicKey.php, phpseclib/Crypt/EC/PrivateKey.php, phpseclib/Crypt/EC/PublicKey.php, phpseclib/Crypt/RSA.php, phpseclib/Crypt/RSA/Formats/Keys/MSBLOB.php, phpseclib/Crypt/RSA/Formats/Keys/PuTTY.php, phpseclib/File/ASN1.php, phpseclib/File/X509.php, phpseclib/Math/BigInteger.php, phpseclib/Math/BigInteger/Engines/BCMath.php, phpseclib/Math/BigInteger/Engines/BCMath/Reductions/Barrett.php, phpseclib/Math/BigInteger/Engines/Engine.php, phpseclib/Math/BigInteger/Engines/GMP.php, phpseclib/Math/BigInteger/Engines/PHP/Reductions/Barrett.php, phpseclib/Net/SFTP.php, phpseclib/Net/SFTP/Stream.php, phpseclib/Net/SSH2.php
This PR attempts to remediate the `Possible Variable Overwrite: Global Scope` vulnerability (CWE 473).
I opened PR #2045, but it was reverted due to too many failed tests.
Basically, it fails because the `EXTR_SKIP` parameter in `extract()` function were not writing values in existing variables, which is not the intended behavior in some cases.
So I'm proposing a new approach: replace `extract()` with variable assignment.
In addition to preventing user input from rewriting global variables, this improves code readability, as it becomes clear which variables are being assigned.
=> Remove extract function - Possible Variable Overwrite

phpseclib/Common/Functions/Strings.php, phpseclib/Crypt/Common/Formats/Keys/PKCS8.php, phpseclib/Crypt/Common/Formats/Keys/PuTTY.php, phpseclib/Crypt/DSA/Formats/Keys/PuTTY.php, phpseclib/Crypt/DSA/PrivateKey.php, phpseclib/Crypt/DSA/PublicKey.php, phpseclib/Crypt/EC/PrivateKey.php, phpseclib/Crypt/EC/PublicKey.php, phpseclib/Crypt/RSA.php, phpseclib/Crypt/RSA/Formats/Keys/MSBLOB.php, phpseclib/Crypt/RSA/Formats/Keys/PuTTY.php, phpseclib/File/ASN1.php, phpseclib/File/X509.php, phpseclib/Math/BigInteger.php, phpseclib/Math/BigInteger/Engines/BCMath.php, phpseclib/Math/BigInteger/Engines/BCMath/Reductions/Barrett.php, phpseclib/Math/BigInteger/Engines/Engine.php, phpseclib/Math/BigInteger/Engines/GMP.php, phpseclib/Math/BigInteger/Engines/PHP/Reductions/Barrett.php, phpseclib/Net/SFTP.php, phpseclib/Net/SFTP/Stream.php, phpseclib/Net/SSH2.php
This PR attempts to remediate the Possible Variable Overwrite: Global Scope vulnerability (CWE 473).
I opened PR https://github.com/phpseclib/phpseclib/pull/2063, but it uses PHP 7.1+ features and has been merged into the `master` branch.
This one replaces `extract()` function by using PHP 5 features, targeting the `3.0` branch.
=> [3.0] Remove extract function - Possible Variable Overwrite
